#Day 3 Assignment


In [7]:
#Day 3 Assignment
# Question 1: Answer
import numpy as np
ar = np.array([range(2,50,3)])
print(ar)

[[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]]


In [ ]:
# Question 2 : Answer
import numpy as np
l1 = [int(x) for x in input().split(",")]
l2 = [int(x) for x in input().split(",")]
arr1= np.array(l1)
arr2= np.array(l2)
arrfinal= np.concatenate((arr1,arr2))
print(arrfinal)
print(np.sort(arrfinal))



In [4]:

#Question 3 : Answer
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
sizeofarray=np.size(arr1)
dimensionofarray = np.shape(arr1)
print(sizeofarray)
print(dimensionofarray)
                 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)


In [9]:
#Question 4 : Answer
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
print(np.shape(arr1))

#1d to 2d array using np.newaxis
arr2 = arr1[:,np.newaxis]
print(arr2)
print(np.shape(arr2))

arr3 = arr1[np.newaxis,:]
print(arr3)
print(np.shape(arr3))

#1d to 2d array using np.expand_dims

arr4 =np.expand_dims(arr1,axis =0) # equivalent to arr1[np.newaxis,:]
print(arr4)
print(np.shape(arr4))

arr5 =np.expand_dims(arr1,axis =1) # equivalent to arr1[:,np.newaxis]
print(arr5)
print(np.shape(arr5))

(6,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[[1 2 3 4 5 6]]
(1, 6)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [6]:

#Question 5: Answer
import numpy as np

arr1 = np.array([[1,2],[4,5]])
arr2 = np.array([[7,8],[11,12]])
                 
print(np.shape(arr1))
print(np.shape(arr2))

# vstack
vrr = np.vstack((arr1,arr2))
print(vrr)

#hstack
hrr = np.hstack((arr1,arr2))
print(hrr)

(2, 2)
(2, 2)
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [11 12]]
[[ 1  2  7  8]
 [ 4  5 11 12]]


In [8]:

#Question 6: Answer
import numpy as np
ls = ["Apple","Apple","Mango","Orange","stawberry","papaya","papaya","Mango"]
print(np.unique(ls,return_counts=True))


lI = [1,2,4,5,6,3,2,7,8,8,6]
print(np.unique(lI,return_counts=True))


(array(['Apple', 'Mango', 'Orange', 'papaya', 'stawberry'], dtype='<U9'), array([2, 2, 1, 2, 1]))
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([1, 2, 1, 1, 1, 2, 1, 2]))
